### ISSUE TITLE
VideoOnDemand from youtube.com issue

### ISSUE THREAD

**Issue by SlazE888** [3dyd/issues-ys#10]
For this example filter can't play nonDASH stream and DASH VO tracks with Resolution="720p":
 [https://www.youtube.com/watch?v=qwUSd-pGyFM](url)
 I'm noticed that through Google Chrome video can be played as 720p.
 Why DASH VO tracks with Resolution="720p" appear only with Filter_v2.0 and didn't appear with Filter_v1.1 ? I'm also noticed that tracks selected in red rectangles on picture can't be played.
![Untitled](https://user-images.githubusercontent.com/53570520/63643751-5d315980-c6e0-11e9-916d-665672f3ea1e.png)

**Comment by 3dyd** [comment]
fixed in 2.0 beta 6
