### ISSUE TITLE
VideoOnDemand from facebook.com issue

### ISSUE THREAD

**Issue by SlazE888** [3dyd/issues-ys#11]
Sometimes filter(with default settings) didn't shows DASH streams(on "Formats" window) from facebook.com site. And I checked, all DASH streams from these VideoOnDemand examples works:
 [https://www.facebook.com/GoTuneOfficial/videos/1615660441806651/](url)
 [https://www.facebook.com/ProFightLeague/videos/440107956586215/](url)
 [https://www.facebook.com/lentaru/videos/1315951725223374/](url)

**Comment by 3dyd** [comment]
fixed in 2.0 beta 6
