### ISSUE TITLE
Videos from vimeo.com issue

### ISSUE THREAD

**Issue by SlazE888** [3dyd/issues-ys#15]
I'm noticed that videos from **vimeo.com** in beta 6 sometimes opens with DASH streams(btw they all doesn't work) and sometimes without DASH(see picture). I'm also noticed that after disabling setting-"Process unknown URLs" video always openes without DASH streams. Example:
[https://vimeo.com/93549616](url)
![vimeo com](https://user-images.githubusercontent.com/53570520/64371196-ac548400-d028-11e9-8f12-baff8fdc230a.jpg)

**Comment by 3dyd** [comment]
Result with DASH comes from youtube-dl, without - from internal analysis.

These DASH streams are fragmented. LAV Splitter currently cannot play fragmented DASH streams, so if you are using it, they will be unplayable.

Tuned default criteria to exclude fragmented DASH streams by default. Nothing else can be done within the filter.
