### ISSUE TITLE
Filter logic algorithm issue_№2

### ISSUE THREAD

**Issue by SlazE888** [3dyd/issues-ys#17]
Because i didn't found the way how to reopen issues on github. I'm create new one, because issue #8 need to be reopen. I don't understand how Criteria testing can help to avoid such issues? it just confirms that filter still have problem with logic algorithm, please see selected area on picture bellow. This is another one example that have exactly the same issues:
 https://www.youtube.com/watch?v=Lu2J6g99Gk0

My logic algorithm was like this:
{
    "chain" : [
        {
            "chain" : [
                {
                    "condition" : "contains",
                    "mapping" : "media.url",
                    "type" : "textual",
                    "value" : "/watch?v="
                },
                {
                    "condition" : "is_equal_to",
                    "mapping" : "property",
                    "negated" : true,
                    "optional" : true,
                    "property" : "streams_count",
                    "source" : "container",
                    "type" : "numeric",
                    "value" : 2
                },
                {
                    "condition" : "is_the_closest_below",
                    "mapping" : "property",
                    "presentation" : "%1%fps",
                    "property" : "framerate",
                    "source" : "video",
                    "threshold" : 7,
                    "type" : "numeric",
                    "value" : 60
                },
                {
                    "condition" : "is_the_closest_below",
                    "mapping" : "video.resolution",
                    "type" : "numeric",
                    "value" : "720p"
                },
                {
                    "condition" : "is_the_closest_below",
                    "mapping" : "property",
                    "property" : "height",
                    "source" : "video",
                    "type" : "numeric",
                    "value" : 720
                },
                {
                    "condition" : "has_the_maximum_value",
                    "mapping" : "property",
                    "optional" : true,
                    "presentation" : "%z{bps,kbps,mbps,gbps}",
                    "property" : "bitrate",
                    "source" : "video",
                    "threshold" : 5,
                    "type" : "numeric"
                },
                {
                    "condition" : "has_the_maximum_value",
                    "mapping" : "property",
                    "optional" : true,
                    "presentation" : "%z{b,kb,mb,gb}",
                    "property" : "size",
                    "source" : "container",
                    "threshold" : 10,
                    "type" : "numeric"
                },
                {
                    "condition" : "has_the_maximum_value",
                    "mapping" : "property",
                    "optional" : true,
                    "presentation" : "%z{bps,kbps,mbps,gbps}",
                    "property" : "bitrate",
                    "source" : "container",
                    "threshold" : 5,
                    "type" : "numeric"
                }
            ],
            "condition" : "AND",
            "type" : "chain"
        }
    ],
    "condition" : "OR",
    "type" : "chain"
}

![Filter logic algorithm issue](https://user-images.githubusercontent.com/53570520/65834057-ce67bc00-e2df-11e9-8a94-c53fcb41dc86.png)

**Comment by SlazE888** [comment]
This is another one example that also have issues with logic algorithm(please see selected area on picture bellow), at this time with incorrect FPS count:
 https://www.youtube.com/watch?v=q_UymU5pKeg

My logic algorithm was like this:
{
    "chain" : [
        {
            "chain" : [
                {
                    "condition" : "contains",
                    "mapping" : "media.url",
                    "type" : "textual",
                    "value" : "/watch?v="
                },
                {
                    "condition" : "is_equal_to",
                    "mapping" : "property",
                    "negated" : true,
                    "optional" : true,
                    "property" : "streams_count",
                    "source" : "container",
                    "type" : "numeric",
                    "value" : 2
                },
                {
                    "condition" : "is_the_closest_below",
                    "mapping" : "property",
                    "presentation" : "%1%fps",
                    "property" : "framerate",
                    "source" : "video",
                    "threshold" : 7,
                    "type" : "numeric",
                    "value" : 60
                },
                {
                    "condition" : "is_the_closest_above",
                    "mapping" : "property",
                    "presentation" : "%1%fps",
                    "property" : "framerate",
                    "source" : "video",
                    "threshold" : 7,
                    "type" : "numeric",
                    "value" : 32
                },
                {
                    "condition" : "is_the_closest_below",
                    "mapping" : "video.resolution",
                    "type" : "numeric",
                    "value" : "3072p"
                },
                {
                    "condition" : "is_the_closest_below",
                    "mapping" : "property",
                    "property" : "height",
                    "source" : "video",
                    "type" : "numeric",
                    "value" : 3072
                },
                {
                    "condition" : "has_the_maximum_value",
                    "mapping" : "property",
                    "optional" : true,
                    "presentation" : "%z{bps,kbps,mbps,gbps}",
                    "property" : "bitrate",
                    "source" : "video",
                    "threshold" : 5,
                    "type" : "numeric"
                },
                {
                    "condition" : "has_the_maximum_value",
                    "mapping" : "property",
                    "optional" : true,
                    "presentation" : "%z{b,kb,mb,gb}",
                    "property" : "size",
                    "source" : "container",
                    "threshold" : 10,
                    "type" : "numeric"
                },
                {
                    "condition" : "has_the_maximum_value",
                    "mapping" : "property",
                    "optional" : true,
                    "presentation" : "%z{bps,kbps,mbps,gbps}",
                    "property" : "bitrate",
                    "source" : "container",
                    "threshold" : 5,
                    "type" : "numeric"
                }
            ],
            "condition" : "AND",
            "type" : "chain"
        }
    ],
    "condition" : "OR",
    "type" : "chain"
}

![Filter logic algorithm issue_2](https://user-images.githubusercontent.com/53570520/65834547-b5add500-e2e4-11e9-839c-6561ff8ea69b.png)

**Comment by 3dyd** [comment]
You can comment in the closed ticket in such case. Notification anyway will be sent.

Regarding to the subject. This behavior is caused by "Equality Threshold" feature. You may read 2.1 changelog and Numeric criteria documentation for details. Logging in the test window has also been improved to reflect that equality threshold is used in such cases.
