### ISSUE TITLE
LiveTV stream from ok.ru issue

### ISSUE THREAD

**Issue by SlazE888** [3dyd/issues-ys#2]
Examples:
 [https://ok.ru/videoembed/73364](url)
 [https://ok.ru/video/73314](url)

Why LAVSplitter can't connect to 3DYDFilter output pin? If I try to connect to LAVSplitter pin manually i got this error in GraphStudio:  
 "Connecting Pins [VFW_E_NO_ACCEPTABLE_TYPES (0x80040207)]"
I try to add in filter(and configure it as External) FFMPEG libraries from here, but it doesn't help and i still unable to play video: 
 [https://ffmpeg.zeranoe.com/builds/win32/shared/](url)
I'm noticed that after installing FFMPEG I can see that the video can be uploaded by this command:
 youtube-dl.exe -v https://ok.ru/videoembed/73364

P.S. I'm installing FFMPEG like this:
 1) Download latest Zeranoe FFMPEG-build
 2) Unpack by 7-Zip to this folder: C:\ffmpeg\
 3) Run as Admin in CMD(not Power Shell!):
  setx /M PATH "C:\ffmpeg\bin;%PATH%

**Comment by 3dyd** [comment]
This site uses HLS streams. To access them HTTP headers collected by youtube-dl must be passed to downloader. This is not a problem for internal downloader but in case of HLS streams actual downloading is performed by downstream filter. And there are no way to pass HTTP headers to it.

**Comment by 3dyd** [comment]
Okay, I have an idea. But it better to wait until initial version is released. Putting this on hold for now.

**Comment by SlazE888** [comment]
> Okay, I have an idea. But it better to wait until initial version is released. Putting this on hold for now.

Really glad to hear that! Maybe filter can play at least VideosOnDemand? Example:
[https://ok.ru/videoembed/966465489562](url)

**Comment by 3dyd** [comment]
HLS can be played now (in 2.1) using "HLS relay" feature.

**Comment by SlazE888** [comment]
> HLS can be played now (in 2.1) using "HLS relay" feature.

Why HLS relay feature is unclickable? Does it have really affect much on all URLs that didn't need it after enabling this feature?

**Comment by 3dyd** [comment]
It is disabled when Properties page is invoked from within video player. It is enabled when using configuration window (from start menu or using config.bat in case of standalone filters). I'll change this behavior to avoid confusion.

Currently when enabled it affects all HLS URLs and only HLS URLs.

**Comment by 3dyd** [comment]
Behavior was changed in 2.1 beta 2.
