### ISSUE TITLE
Videos from vimeo.com issue_№3

### ISSUE THREAD

**Issue by SlazE888** [3dyd/issues-ys#20]
Filter shows wrong information about video streams, please see picture bellow. Example:
https://vimeo.com/363235870
![Untitled](https://user-images.githubusercontent.com/53570520/66421861-53a24d80-ea11-11e9-9424-329117be47b6.png)

**Comment by 3dyd** [comment]
Fixed in 2.1 beta 3.

**Comment by SlazE888** [comment]
> Fixed in 2.1 beta 3.

Many thanks! May be closed :)

**Comment by SlazE888** [comment]
This ticket need to be reopened because from now filter didn't shows H265 and HDR streams, more over the best by Resolution track have only **1920x** but if I start to play it through Google Chrome browser i can choose **2K** and **4K** tracks. Whats up?
