### ISSUE TITLE
VideoOnDemand from mail.ru issue

### ISSUE THREAD

**Issue by SlazE888** [3dyd/issues-ys#3]
Examples:
 [https://my.mail.ru/video/embed/510456420747968766](url)
 [https://my.mail.ru/video/embed/602962354082250062](url)

Why LAVSplitter can't connect to 3DYDFilter output pin? If I try to connect to LAVSplitter pin manually i got this error in GraphStudio:  
 "Connecting Pins [VFW_E_NO_ACCEPTABLE_TYPES (0x80040207)]"
I try to add in filter(and configure it as External) FFMPEG libraries from here, but it doesn't help and i still unable to play video: 
 [https://ffmpeg.zeranoe.com/builds/win32/shared/](url)
I'm noticed that after installing FFMPEG I can see that the video can be uploaded by this command:
 youtube-dl.exe -v https://my.mail.ru/video/embed/510456420747968766

P.S. I'm installing FFMPEG like this:
 1) Download latest Zeranoe FFMPEG-build
 2) Unpack by 7-Zip to this folder: C:\ffmpeg\
 3) Run as Admin in CMD(not Power Shell!):
  setx /M PATH "C:\ffmpeg\bin;%PATH%

**Comment by 3dyd** [comment]
Should be fixed in 2.0 beta 4. Feel free to reopen if it is still a problem.
