### ISSUE TITLE
VideoOnDemand from tvigle.ru issue

### ISSUE THREAD

**Issue by SlazE888** [3dyd/issues-ys#4]
I have issue after seeking(but **on HLS-tracks only**!), time counter starts count the time but i didn't hear sound and just instead of video I see just one frame. To reproduce:
1) Open this URL in filter in Graph Studio:
 [https://www.tvigle.ru/video/chiko-i-rita/](url)
2) Render filter output pin.
3) Start the graph and wait at least two seconds.
4) Press "Ctrl+K" buttons and press "Seek" button there(seeking must starting from 00:00:00.000).

**Comment by 3dyd** [comment]
What splitter did you use? LAV Splitter?

**Comment by SlazE888** [comment]
> What splitter did you use? LAV Splitter?

yes!

**Comment by 3dyd** [comment]
This issue comes from LAV Splitter. See Nevcairiel/LAVFilters#306

**Comment by SlazE888** [comment]
Fixed in LAVFilters_v0.74.1-98.
