### ISSUE TITLE
LiveTV stream from livehlsvgtrk.cdnvideo.ru issue

### ISSUE THREAD

**Issue by SlazE888** [3dyd/issues-ys#5]
HLS redirect TV-stream examples:
 [https://livehlsvgtrk.cdnvideo.ru/iframe/stream/live_id/2961](url)
 [https://livehlsvgtrk.cdnvideo.ru/iframe/stream/live_id/19201](url)
 [https://livehlsvgtrk.cdnvideo.ru/iframe/stream/live_id/4941](url)
 [https://livehlsvgtrk.cdnvideo.ru/iframe/stream/live_id/21](url)

Why LAVSplitter can't connect to 3DYDFilter output pin? If I try to connect to LAVSplitter pin manually i got this error in GraphStudio:
 "Connecting Pins [VFW_E_NO_ACCEPTABLE_TYPES (0x80040207)]"
I'm noticed that video can be uploaded by this command:
 youtube-dl.exe -v https://livehlsvgtrk.cdnvideo.ru/iframe/stream/live_id/2961

**Comment by 3dyd** [comment]
Confirmed it to be the same as #2 i.e. requiring HTTP headers from youtube-dl to be passed to downloader. Closing as duplicate.
