### ISSUE TITLE
Filter logic algorithm issue

### ISSUE THREAD

**Issue by SlazE888** [3dyd/issues-ys#8]
Parameters "container.size" and "video.bitrate" works incorrectly if resolution is 720p(please see picture). Example:
[https://www.youtube.com/watch?v=D22mqYFniNk](url)

Why it not happen if resolution is 240p, in both cases difference in size is the same?!

![Q-90](https://user-images.githubusercontent.com/53570520/63642099-7cb98980-c6c2-11e9-881d-901c3a9dfd78.png)
](url)

**Comment by 3dyd** [comment]
To deal with such cases a feature called "criteria testing" was implemented. At the moment it is available only in foo_youtube ([read more](https://fy.3dyd.com/help/criteria/#Criteria_testing)) but I will try to add it to the filter before initial release.

For now you can use it in foo_youtube (preferences `Decoding -> Video -> Quality`). Criteria in the filter and foo_youtube are compatible, so you can just copy yours from the filter (right click on top-level `OR` in Configuration window and select `Copy`) and paste it in criteria configuration window from foo_youtube.

**Comment by 3dyd** [comment]
Added a way in beta 8 to access and edit criteria from quality selection window (using context menu -> "Configure"). So criteria testing now can be used from within this window. More info is in the help topic "Criteria" on the site.
