### ISSUE TITLE
"User-Agent" string issue

### ISSUE THREAD

**Issue by SlazE888** [3dyd/issues-ys#9]
HLS Examples:
 [http://cdn-01.bonus-tv.ru/TVB7/vmesterf/playlist.m3u8](url)
 [https://cdn-01.bonus-tv.ru:8090/radostmoya_edge/index.m3u8](url)
I try all these agents, but streams didn't start to play(they all works in VLC for both examples above):
  **VLPLAYER/8.5**
  **Mozilla/5.0**
  **Mozilla**
  **BASS/2.4**
  **Lavf/57.83.100**
  **FreeIPTV**

**Comment by 3dyd** [comment]
Same as #2: it can be played only if downstream filter uses proper HTTP headers.
